background            #1B1A1C

color0                #1B1A1C
color1                #CD5FFF
color2                #64DBED
color3                #FFDCF1
color4                #87AED2
color5                #BC9CE7
color6                #89D3F0
color7                #E8D3DD
color8                #C5B5BE
color9                #E8A9FF
color10               #F9FEFF
color11               #FFFFFF
color12               #C5DFF3
color13               #EAD0FF
color14               #F3FBFF
color15               #E3E2E7

cursor                #E8D3DD

foreground            #E8D3DD

selection_background  #E2E1EC
selection_foreground  #45464F

# Override obscure colors for starship prompt (these are greys at the end)
color255              #C4C5D6
color254              #444654
color253              #C6C5D0
color252              #45464F
color251              #C2C5DD
color250              #8C90A6
color249              #FFB4AB
color248              #93000A

color232              #2D303D
color233              #E0E1F3
color234              #2F3038
color235              #E2E1EC
color236              #2C3042
color237              #000000
color238              #690005
color239              #FFDAD6
color240              #2D303D
# Somehow 232 doesn't work so i gotta use another number

# Some stuff should specifically use the colors in the middle so they look acceptable in both unthemed light/dark
color243              #C4C5D6
color244              #FFB4AB
color245              #474648

